### ISSUE TITLE
Idea - convert to dokuwiki plugin

### ISSUE THREAD

**Issue by tomquinn04** [davidjimenez75/dokuwiki-smileys-local#1]
Hi,

I need a plugin to add emojis to my dokuwiki. I've tried yours but it can't work for two reasons:

1, we use canonical URLs with slash namespace separators so I can't figure out how you access the lib folder from a browser.
2, that script allows anybody to upload emojis which isn't ok

Would you be willing to try to upgrade your script to a plugin? There is an outdated one here but I can't get it to install: https://www.dokuwiki.org/plugin:symbols

Thanks in advance,
Tom

**Comment by tomquinn04** [comment]
I just looked at the web archive, here is a working download link for the plugin https://web.archive.org/web/20191028095045/http://www.tux-tips.de/tux-wiki/doku.php?id=start:dokuwiki:plugins:symbols

**Comment by davidjimenez75** [comment]
Hi Tom

You can change the url's of the "smileys" images using relative paths in the conf/smileys.local.conf

Maybe you can add your personal "smileys" folder "local" to the global icons folder of Apache2.

That would looks like this:

```
8-)         ../../../icons/local/emojione-smileys/smiling-face-with-sunglasses.png
```

The urls for the images will be something like this:

```
https://example.com/lib/images/smileys/../../../icons/local/emojione-smileys/smiling-face-with-sunglasses.png
```
With is equivalent to:

```
https://example.com/icons/local/emojione-smileys/smiling-face-with-sunglasses.png
```

Remember every time to open and save (to change the file date of the conf/dokuwiki.php)  so Dokuwiki detects a configuration change and update the changes done on conf/smileys.local.conf

**Comment by tomquinn04** [comment]
Thanks!
